name: Show Me the S3cr3tz
on: [push]

env:
  ENV_SECRET: ${{ secrets.ENV_SECRET }}
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
  ENV_VAR: ${{ vars.ENV_VAR }}
  REPO_VAR: ${{ vars.REPO_VAR }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set env as secret
        run: |
          import os
          print("ENV_SECRET:")
          for q in (os.getenv("ENV_SECRET")):
            print(q)
          print("REPO_SECRET:")
          for q in (os.getenv("REPO_SECRET")):
            print(q)
          print("ENV_VAR:")
          for q in (os.getenv("ENV_VAR")):
            print(q)
          print("REPO_VAR:")
          for q in (os.getenv("REPO_VAR")):
            print(q)
        shell: python
